name: strwae
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - charset-normalizer=2.0.4
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy-base=1.26.3
  - openh264=2.1.1
  - openssl=1.1.1u
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.11
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.29.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - torchtriton=2.0.0
  - typing_extensions=4.5.0
  - unzip=6.0
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.4.2
  - zip=3.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - appdirs==1.4.4
    - brotlipy==0.7.0
    - cffi==1.15.1
    - click==8.1.3
    - contourpy==1.1.0
    - cryptography==39.0.1
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - fonttools==4.40.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - gmpy2==2.1.2
    - h5py==3.12.1
    - joblib==1.4.2
    - kiwisolver==1.4.4
    - lightning-utilities==0.11.8
    - markupsafe==2.1.1
    - matplotlib==3.7.1
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - mpmath==1.2.1
    - numpy==1.26.3
    - packaging==23.1
    - pandas==2.0.2
    - pathtools==0.1.2
    - pillow==9.4.0
    - platformdirs==4.3.6
    - protobuf==4.23.3
    - psutil==5.9.5
    - pyparsing==3.1.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - scikit-learn==1.5.2
    - scipy==1.13.0
    - sentry-sdk==2.18.0
    - setproctitle==1.3.2
    - setuptools==67.8.0
    - six==1.16.0
    - smmap==5.0.0
    - threadpoolctl==3.5.0
    - torch==2.0.1
    - torch-fidelity==0.3.0
    - torchmetrics==1.5.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - triton==2.0.0
    - tzdata==2023.3
    - wandb==0.18.5
